name: Example workflow for Python using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Count total number of vulnerabilities
        run: |
          RESULTS_LENGTH=$(jq '.runs[0].results | length' snyk.sarif)
          echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
          echo $RESULTS_LENGTH
      - name: Slack Alert
      - uses: 8398a7/action-slack@v3
        with:
           status: ${{ job.status }}
           fields: repo,commit,author,eventName,ref
           text: |
                *The Snyk scan result for repo is ${{ job.status }}*
                *Number of vulnarabilities : ${{ env.RESULTS_LENGTH }}*
                *Detail*: https://github.com/${{ github.repository }}/actions/runs/$ {{ github.run_id }}
        env:
           SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        if: always() # Pick up events even if the job fails or is canceled.
